<a href="https://colab.research.google.com/github/lucasalechilet/Curso_FCD/blob/main/L1_lib_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#1. Carga y estructuración de datos

In [1]:
import numpy as np
np.random.seed(42) # seteamos el seed en 42 para reproducibilidad


precios_acciones = np.random.uniform(low=500, high=1500, size=(5, 5)) #array de 5x5 con datos uniformes, entre 500 y 1500
precios_acciones = np.round(precios_acciones, 1) #redondeamos a 1 decimal

print("Precios de Acciones")
print(precios_acciones)
print("\n")



Precios de Acciones
[[ 874.5 1450.7 1232.  1098.7  656. ]
 [ 656.   558.1 1366.2 1101.1 1208.1]
 [ 520.6 1469.9 1332.4  712.3  681.8]
 [ 683.4  804.2 1024.8  931.9  791.2]
 [1111.9  639.5  792.1  866.4  956.1]]




2. Análisis y Transformación de Datos

In [3]:
promedio_por_accion = np.mean(precios_acciones, axis=1)  #usando numpy, basta usar estos comandos para promediar y obtener min y max
maximo_por_accion = np.max(precios_acciones, axis=1)      #según corresponda. usamos axis=1 para variar sobre día
minimo_por_accion = np.min(precios_acciones, axis=1)

print(f"Promedio: {np.round(promedio_por_accion, 2)}")
print(f"Máximo: {maximo_por_accion}")
print(f"Mínimo: {minimo_por_accion}\n")

variacion_diaria = (precios_acciones[:, 1:] - precios_acciones[:, :-1]) / precios_acciones[:, :-1] * 100  # para calcular variacion porcentual diaria usamos
                                                                                                          #(Precio de hoy - Precio de ayer) / Precio de ayer * 100
                                                                                                          # [:,1:] significa tomar todas las filas, y de las columnas
                                                                                                          #ignoramos el primer valor
                                                                                                          # [:, :-1] significa tomar todas las filas, y de las columnas
                                                                                                          #tomar todos menos el último valor
                                                                                                          #así, podemos aplicar la operación correspondiente para la variación
print("Variación Porcentual Diaria (%)")
print(np.round(variacion_diaria, 1))
print("\n")

#calcularemos normalización
min_dims = minimo_por_accion.reshape(-1, 1)  #reajustamos ambos vectores para aplicar el cálculo a continuación
max_dims = maximo_por_accion.reshape(-1, 1)
precios_normalizados = (precios_acciones - min_dims) / (max_dims - min_dims) #fórmula utilizada: (X - X_min) / (X_max - X_min)

print("Precios Normalizados")
print(np.round(precios_normalizados, 1))
print("\n")

Promedio: [1062.38  977.9   943.4   847.1   873.2 ]
Máximo: [1450.7 1366.2 1469.9 1024.8 1111.9]
Mínimo: [656.  558.1 520.6 683.4 639.5]

Variación Porcentual Diaria (%)
[[ 65.9 -15.1 -10.8 -40.3]
 [-14.9 144.8 -19.4   9.7]
 [182.3  -9.4 -46.5  -4.3]
 [ 17.7  27.4  -9.1 -15.1]
 [-42.5  23.9   9.4  10.4]]


Precios Normalizados
[[0.3 1.  0.7 0.6 0. ]
 [0.1 0.  1.  0.7 0.8]
 [0.  1.  0.9 0.2 0.2]
 [0.  0.4 1.  0.7 0.3]
 [1.  0.  0.3 0.5 0.7]]




3. Optimización y Selección de Datos

In [7]:
#buscamos variación diaria de acción 5 en día 3
rendimiento_especifico = variacion_diaria[4, 1]

precios_altos = precios_acciones[precios_acciones > 1000]

print(f"Precio de la acción 5 en el día 3: ${rendimiento_especifico}")
print(f"Precios totales que superaron los $100: {precios_altos}")

Precio de la acción 5 en el día 3: $23.86239249413605
Precios totales que superaron los $100: [1450.7 1232.  1098.7 1366.2 1101.1 1208.1 1469.9 1332.4 1024.8 1111.9]


4. Comparación con otros métodos

Usar listas nativas de Python para este análisis nos obligaría a escribir bucles anidados lentos y propensos a errores. Con NumPy, gracias a la vectorización y el broadcasting, reducimos el código a un par de operaciones limpias que se ejecutan casi instantáneamente. Es un salto técnico fundamental para dejar de procesar datos como un script básico y empezar a estructurar matrices con el rendimiento real requerido.

5. Conclusiones

En conclusión, integrar NumPy es un paso obligatorio para que esta herramienta financiera sea realmente escalable y capaz de procesar datos en tiempo real. Al aprovechar la vectorización "embebida", eliminamos los cuellos de botella de Python y dejamos nuestras matrices limpias, estructuradas y listas para utilizarse.